// Package crud provides generic CRUD operations for any GORM model.
// Tenant scoping and user tracking are handled automatically by the
// gocore mixin callbacks (TenantMixin, TrackedMixin) — callers just
// pass the context.
package crud

import (
	"context"
	"fmt"
	"reflect"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// FindByID retrieves a single record by its primary key.
// Tenant scoping is applied automatically via GORM callbacks.
func FindByID[T any](ctx context.Context, db *gorm.DB, id uuid.UUID) (*T, error) {
	var result T
	if err := db.WithContext(ctx).First(&result, id).Error; err != nil {
		return nil, err
	}
	return &result, nil
}

// FindByIDWithPreload retrieves a single record by primary key with eager-loaded relations.
func FindByIDWithPreload[T any](ctx context.Context, db *gorm.DB, id uuid.UUID, preload ...string) (*T, error) {
	var result T
	query := db.WithContext(ctx)
	for _, rel := range preload {
		query = query.Preload(rel)
	}
	if err := query.First(&result, id).Error; err != nil {
		return nil, err
	}
	return &result, nil
}

// List retrieves all records of a type.
// Tenant scoping is applied automatically via GORM callbacks.
func List[T any](ctx context.Context, db *gorm.DB) ([]*T, error) {
	var results []*T
	if err := db.WithContext(ctx).Find(&results).Error; err != nil {
		return nil, err
	}
	return results, nil
}

// ListWithFilter retrieves records matching the filter conditions.
// Pass a struct with non-zero fields to filter by, or a map.
func ListWithFilter[T any](ctx context.Context, db *gorm.DB, filter interface{}) ([]*T, error) {
	var results []*T
	query := db.WithContext(ctx)
	if filter != nil {
		query = query.Where(filter)
	}
	if err := query.Find(&results).Error; err != nil {
		return nil, err
	}
	return results, nil
}

// Count returns the total number of records matching optional filter conditions.
func Count[T any](ctx context.Context, db *gorm.DB, filter interface{}) (int64, error) {
	var model T
	var count int64
	query := db.WithContext(ctx).Model(&model)
	if filter != nil {
		query = query.Where(filter)
	}
	if err := query.Count(&count).Error; err != nil {
		return 0, err
	}
	return count, nil
}

// Create inserts a new record. The primary key is generated by the database.
// Tenant ID and created_by/updated_by are set automatically via callbacks.
func Create[T any](ctx context.Context, db *gorm.DB, record *T) (*T, error) {
	if err := db.WithContext(ctx).Create(record).Error; err != nil {
		return nil, err
	}
	return record, nil
}

// Update modifies an existing record. Only non-zero fields in updates are applied.
// Tenant scoping ensures you can only update records in your own tenant.
func Update[T any](ctx context.Context, db *gorm.DB, id uuid.UUID, updates interface{}) (*T, error) {
	var result T
	if err := db.WithContext(ctx).First(&result, id).Error; err != nil {
		return nil, err
	}
	if err := db.WithContext(ctx).Model(&result).Updates(updates).Error; err != nil {
		return nil, err
	}
	if err := db.WithContext(ctx).First(&result, id).Error; err != nil {
		return nil, err
	}
	return &result, nil
}

// Save persists changes to an existing record.
// Use this after calling model methods that modify fields.
func Save[T any](ctx context.Context, db *gorm.DB, record *T) (*T, error) {
	if err := db.WithContext(ctx).Save(record).Error; err != nil {
		return nil, err
	}
	return record, nil
}

// Delete soft-deletes a record by primary key (if the model has SoftDeleteMixin)
// or hard-deletes if it doesn't.
func Delete[T any](ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	var model T
	if err := db.WithContext(ctx).First(&model, id).Error; err != nil {
		return fmt.Errorf("record not found: %w", err)
	}
	return db.WithContext(ctx).Delete(&model).Error
}

// Paginated represents a page of results with metadata.
type Paginated[T any] struct {
	Items      []T
	TotalCount int64
}

// ListPaginated retrieves a page of records with total count.
// Pass relation names in preload to eagerly load associations.
func ListPaginated[T any](ctx context.Context, db *gorm.DB, filter interface{}, limit, offset int, preload ...string) (*Paginated[T], error) {
	var results []T
	var total int64
	var model T

	query := db.WithContext(ctx).Model(&model)
	if filter != nil {
		query = query.Where(filter)
	}
	if err := query.Count(&total).Error; err != nil {
		return nil, err
	}

	pageQuery := db.WithContext(ctx)
	if filter != nil {
		pageQuery = pageQuery.Where(filter)
	}
	for _, rel := range preload {
		pageQuery = pageQuery.Preload(rel)
	}
	if limit <= 0 {
		limit = 25
	}
	if err := pageQuery.Limit(limit).Offset(offset).Find(&results).Error; err != nil {
		return nil, err
	}

	return &Paginated[T]{Items: results, TotalCount: total}, nil
}

// EnrichBelongsTo is a generic workaround for GORM's belongs_to FK resolution bug.
// When both the source and target models have a field with the same name, GORM
// can pick the wrong one. This function manually batch-loads the target records
// and assigns them.
//
// Parameters:
//   - items: slice of source model structs
//   - fkField: the foreign key field name on the source (e.g., "SkillVersionID")
//   - assocField: the association field name on the source (e.g., "SkillVersion")
//   - target: a zero-value pointer of the target model
//   - pkField: the primary key field name on the target
//   - pkColumn: the primary key column name in the DB
func EnrichBelongsTo[T any, R any](ctx context.Context, db *gorm.DB, items []T, fkField, assocField string, target *R, pkField, pkColumn string) {
	if len(items) == 0 {
		return
	}

	idSet := make(map[uuid.UUID]bool)
	for i := range items {
		v := reflect.ValueOf(&items[i]).Elem()
		fk := v.FieldByName(fkField)
		if !fk.IsValid() {
			return
		}
		id, ok := fk.Interface().(uuid.UUID)
		if ok && id != uuid.Nil {
			idSet[id] = true
		}
	}
	if len(idSet) == 0 {
		return
	}

	ids := make([]uuid.UUID, 0, len(idSet))
	for id := range idSet {
		ids = append(ids, id)
	}

	targetSlice := reflect.MakeSlice(reflect.SliceOf(reflect.TypeOf(target).Elem()), 0, len(ids))
	targetPtr := reflect.New(targetSlice.Type())
	targetPtr.Elem().Set(targetSlice)
	db.WithContext(ctx).Where(pkColumn+" IN ?", ids).Find(targetPtr.Interface())

	loaded := targetPtr.Elem()
	lookup := make(map[uuid.UUID]reflect.Value, loaded.Len())
	for i := 0; i < loaded.Len(); i++ {
		pk := loaded.Index(i).FieldByName(pkField)
		if pk.IsValid() {
			id, ok := pk.Interface().(uuid.UUID)
			if ok {
				elem := loaded.Index(i).Addr()
				lookup[id] = elem
			}
		}
	}

	for i := range items {
		v := reflect.ValueOf(&items[i]).Elem()
		fk := v.FieldByName(fkField)
		id, ok := fk.Interface().(uuid.UUID)
		if !ok {
			continue
		}
		if ptr, exists := lookup[id]; exists {
			assoc := v.FieldByName(assocField)
			if assoc.IsValid() && assoc.CanSet() {
				assoc.Set(ptr)
			}
		}
	}
}

// fieldByPath returns a field on v, descending through an embedded struct
// if the field isn't directly present at the top level.
func fieldByPath(v reflect.Value, embeddedName, fieldName string) reflect.Value {
	embedded := v.FieldByName(embeddedName)
	if embedded.IsValid() {
		return embedded.FieldByName(fieldName)
	}
	return v.FieldByName(fieldName)
}
