package main

import (
	"fmt"
	"strings"
)

// GenerateResolvers produces Go resolver implementations that delegate to the generic CRUD package.
// These are written to a single file that gqlgen will merge with its generated code.
//
// adminMode controls whether the generated static query/mutation resolvers
// emit a per-user auth check (`connection.CurrentUser(ctx) == uuid.Nil`).
// The admin API gates GraphQL with a shared bearer token via AdminAuth
// middleware — there is no current user in that context — so emitting the
// check causes every static resolver to return "not authenticated."
func GenerateResolvers(models []ModelDef, staticMutations []StaticMutationDef, staticQueries []StaticQueryDef, serviceTypes []ServiceTypeDef, moduleName, modelsImportPath string, adminMode bool) string {
	if moduleName == "" {
		moduleName = "core"
	}
	var sb strings.Builder

	// Collect unique service imports
	serviceImports := collectServiceImports(staticMutations, staticQueries)

	// Build a map of service type name → package name for return type resolution
	serviceTypePackage := make(map[string]string)
	for _, st := range serviceTypes {
		serviceTypePackage[st.Name] = st.PackageName
	}

	// Detect whether any static mutation or query param uses time.Time so we
	// know to pull in the "time" standard library import.
	needsTimeImport := false
	for _, m := range staticMutations {
		for _, p := range m.Params {
			if strings.Contains(p.GoType, "time.Time") {
				needsTimeImport = true
			}
		}
	}
	for _, q := range staticQueries {
		for _, p := range q.Params {
			if strings.Contains(p.GoType, "time.Time") {
				needsTimeImport = true
			}
		}
	}

	sb.WriteString(fmt.Sprintf(`// Code generated by tools/gqlgen. DO NOT EDIT.
// CRUD, instance-level, and class-level resolver implementations for all models.

package resolver

import (
	"context"
	"fmt"
	"github.com/mashbot-co/gocore/db/connection"
	"github.com/mashbot-co/gocore/db/crud"
	"%s/graph/generated"
	models %q

	"github.com/google/uuid"
`, moduleName, modelsImportPath))

	if needsTimeImport {
		sb.WriteString("\t\"time\"\n")
	}

	for _, imp := range serviceImports {
		sb.WriteString(fmt.Sprintf("\t%q\n", imp))
	}

	sb.WriteString(")\n\n")

	// Query resolvers
	for _, m := range models {
		pkField := primaryKeyField(m)
		if pkField == nil {
			continue
		}
		// Models that opt out of auto queries supply hand-written Get/List
		// resolvers in the resolver package — usually to enforce authorization
		// (e.g. project list filtered by membership).
		if m.SkipQueries {
			continue
		}

		info := analyzePreloads(m)
		hasPreloads := len(info.Paths) > 0
		preloadArgs := ""
		if hasPreloads {
			var quoted []string
			for _, p := range info.Paths {
				quoted = append(quoted, fmt.Sprintf("%q", p))
			}
			preloadArgs = ", " + strings.Join(quoted, ", ")
		}
		needsEnrich := info.EnrichTenants || info.EnrichUsers || len(info.NestedEnrich) > 0

		pkParam := pkParamName(m)

		// FindByID
		sb.WriteString(fmt.Sprintf("// %s retrieves a single %s by ID.\n", m.Name, toHumanReadable(m.Name)))
		sb.WriteString(fmt.Sprintf("func (r *queryResolver) %s(ctx context.Context, %s uuid.UUID) (*models.%s, error) {\n", m.Name, pkParam, m.Name))
		if !needsEnrich {
			// Simple case — just preload and return.
			if hasPreloads {
				sb.WriteString(fmt.Sprintf("\treturn crud.FindByIDWithPreload[models.%s](ctx, r.DB, %s%s)\n", m.Name, pkParam, preloadArgs))
			} else {
				sb.WriteString(fmt.Sprintf("\treturn crud.FindByID[models.%s](ctx, r.DB, %s)\n", m.Name, pkParam))
			}
		} else {
			// Need post-load enrichment — fetch, enrich, return.
			if hasPreloads {
				sb.WriteString(fmt.Sprintf("\trecord, err := crud.FindByIDWithPreload[models.%s](ctx, r.DB, %s%s)\n", m.Name, pkParam, preloadArgs))
			} else {
				sb.WriteString(fmt.Sprintf("\trecord, err := crud.FindByID[models.%s](ctx, r.DB, %s)\n", m.Name, pkParam))
			}
			sb.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			// EnrichTenants and EnrichUsers both work on a []Model slice, so we
			// build items once and share it if either (or both) is needed.
			if info.EnrichTenants || info.EnrichUsers {
				sb.WriteString(fmt.Sprintf("\titems := []models.%s{*record}\n", m.Name))
				if info.EnrichTenants {
					sb.WriteString("\tcrud.EnrichTenants(ctx, r.DB, items)\n")
				}
				if info.EnrichUsers {
					sb.WriteString("\tcrud.EnrichUsers(ctx, r.DB, items)\n")
				}
				sb.WriteString("\t*record = items[0]\n")
			}
			for _, rel := range info.NestedEnrich {
				sb.WriteString(fmt.Sprintf("\tcrud.EnrichTenants(ctx, r.DB, record.%s)\n", rel))
			}
			sb.WriteString("\treturn record, nil\n")
		}
		sb.WriteString("}\n\n")

		// List with filter and pagination
		plural := pluralize(m.Name)
		hasFilter := len(filterableFields(m)) > 0

		sb.WriteString(fmt.Sprintf("// %s lists %s with optional filtering and pagination.\n", plural, pluralize(toHumanReadable(m.Name))))
		if hasFilter {
			sb.WriteString(fmt.Sprintf("func (r *queryResolver) %s(ctx context.Context, filter *generated.%sFilter, pagination *generated.PaginationInput) (*generated.%sList, error) {\n", plural, m.Name, m.Name))
		} else {
			sb.WriteString(fmt.Sprintf("func (r *queryResolver) %s(ctx context.Context, pagination *generated.PaginationInput) (*generated.%sList, error) {\n", plural, m.Name))
		}

		sb.WriteString("\tlimit, offset := parsePagination(pagination)\n")

		if hasFilter {
			sb.WriteString("\tfilterMap := toFilterMap(filter)\n")
			sb.WriteString(fmt.Sprintf("\tpage, err := crud.ListPaginated[models.%s](ctx, r.DB, filterMap, limit, offset%s)\n", m.Name, preloadArgs))
		} else {
			sb.WriteString(fmt.Sprintf("\tpage, err := crud.ListPaginated[models.%s](ctx, r.DB, nil, limit, offset%s)\n", m.Name, preloadArgs))
		}

		sb.WriteString("\tif err != nil {\n")
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")

		if info.EnrichTenants {
			sb.WriteString("\tcrud.EnrichTenants(ctx, r.DB, page.Items)\n")
		}
		if info.EnrichUsers {
			sb.WriteString("\tcrud.EnrichUsers(ctx, r.DB, page.Items)\n")
		}
		for _, rel := range info.NestedEnrich {
			sb.WriteString(fmt.Sprintf("\tfor i := range page.Items {\n"))
			sb.WriteString(fmt.Sprintf("\t\tcrud.EnrichTenants(ctx, r.DB, page.Items[i].%s)\n", rel))
			sb.WriteString("\t}\n")
		}

		sb.WriteString(fmt.Sprintf("\treturn &generated.%sList{\n", m.Name))
		sb.WriteString("\t\tItems: page.Items,\n")
		sb.WriteString("\t\tPageInfo: toPageInfo(page.TotalCount, limit, offset),\n")
		sb.WriteString("\t}, nil\n")
		sb.WriteString("}\n\n")
	}

	// Mutation resolvers
	for _, m := range models {
		createFields := writableFields(m)
		if len(createFields) == 0 {
			continue
		}
		// Skip auto CRUD for models that opt out — they provide hand-rolled
		// resolvers in the resolver package (e.g., to enforce versioning).
		if m.SkipCRUD {
			continue
		}

		// Create
		sb.WriteString(fmt.Sprintf("// Create%s creates a new %s.\n", m.Name, toHumanReadable(m.Name)))
		sb.WriteString(fmt.Sprintf("func (r *mutationResolver) Create%s(ctx context.Context, input generated.Create%sInput) (*models.%s, error) {\n", m.Name, m.Name, m.Name))
		sb.WriteString(fmt.Sprintf("\trecord := inputToModel[models.%s](input)\n", m.Name))
		sb.WriteString(fmt.Sprintf("\treturn crud.Create[models.%s](ctx, r.DB, record)\n", m.Name))
		sb.WriteString("}\n\n")

		pkParam := pkParamName(m)

		// Update
		sb.WriteString(fmt.Sprintf("// Update%s updates an existing %s by ID.\n", m.Name, toHumanReadable(m.Name)))
		sb.WriteString(fmt.Sprintf("func (r *mutationResolver) Update%s(ctx context.Context, %s uuid.UUID, input generated.Update%sInput) (*models.%s, error) {\n", m.Name, pkParam, m.Name, m.Name))
		sb.WriteString(fmt.Sprintf("\tupdates := updateToMap(input)\n"))
		sb.WriteString(fmt.Sprintf("\treturn crud.Update[models.%s](ctx, r.DB, %s, updates)\n", m.Name, pkParam))
		sb.WriteString("}\n\n")

		// Delete
		sb.WriteString(fmt.Sprintf("// Delete%s deletes a %s by ID.\n", m.Name, toHumanReadable(m.Name)))
		sb.WriteString(fmt.Sprintf("func (r *mutationResolver) Delete%s(ctx context.Context, %s uuid.UUID) (bool, error) {\n", m.Name, pkParam))
		sb.WriteString(fmt.Sprintf("\terr := crud.Delete[models.%s](ctx, r.DB, %s)\n", m.Name, pkParam))
		sb.WriteString("\treturn err == nil, err\n")
		sb.WriteString("}\n\n")
	}

	// Custom mutation resolvers — generated from // graphql:mutation annotations
	for _, m := range models {
		pkParam := pkParamName(m)
		for _, mut := range m.Mutations {
			mutName := toCamelCase(toSnakeCase(mut.MethodName)) + m.Name
			mutName = strings.ToUpper(mutName[:1]) + mutName[1:]

			// Build Go function signature params
			goParams := fmt.Sprintf("ctx context.Context, %s uuid.UUID", pkParam)
			callArgs := ""
			for _, p := range mut.Params {
				goParams += fmt.Sprintf(", %s %s", p.Name, p.GoType)
				callArgs += ", " + p.Name
			}

			// Description
			if mut.Description != "" {
				sb.WriteString(fmt.Sprintf("// %s %s\n", mutName, strings.ToLower(mut.Description[:1])+mut.Description[1:]))
			}

			sb.WriteString(fmt.Sprintf("func (r *mutationResolver) %s(%s) (*models.%s, error) {\n", mutName, goParams, m.Name))
			sb.WriteString(fmt.Sprintf("\trecord, err := crud.FindByID[models.%s](ctx, r.DB, %s)\n", m.Name, pkParam))
			sb.WriteString("\tif err != nil {\n")
			sb.WriteString("\t\treturn nil, err\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\tif err := record.%s(%s); err != nil {\n", mut.MethodName, strings.TrimPrefix(callArgs, ", ")))
			sb.WriteString("\t\treturn nil, err\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\treturn crud.Save(ctx, r.DB, record)\n"))
			sb.WriteString("}\n\n")
		}
	}

	// Class-level (static) mutation resolvers — call model or service functions
	for _, s := range staticMutations {
		var goParams []string
		goParams = append(goParams, "ctx context.Context")
		var callArgs []string
		callArgs = append(callArgs, "ctx", "r.DB")
		for _, p := range s.Params {
			goParams = append(goParams, fmt.Sprintf("%s %s", p.Name, p.GoType))
			callArgs = append(callArgs, p.Name)
		}

		funcName := toPascalCase(s.MutationName)
		pkg := "models"
		if s.PackageName != "" {
			pkg = s.PackageName
		}

		if s.Description != "" {
			sb.WriteString(fmt.Sprintf("// %s %s\n", funcName, strings.ToLower(s.Description[:1])+s.Description[1:]))
		}

		retPkg := "models"
		if p, ok := serviceTypePackage[s.ReturnType]; ok {
			retPkg = p
		}

		if s.ReturnsList {
			sb.WriteString(fmt.Sprintf("func (r *mutationResolver) %s(%s) ([]%s.%s, error) {\n",
				funcName, strings.Join(goParams, ", "), retPkg, s.ReturnType))
		} else {
			sb.WriteString(fmt.Sprintf("func (r *mutationResolver) %s(%s) (*%s.%s, error) {\n",
				funcName, strings.Join(goParams, ", "), retPkg, s.ReturnType))
		}

		if !s.IsPublic && !adminMode {
			sb.WriteString("\tif connection.CurrentUser(ctx) == uuid.Nil {\n")
			sb.WriteString("\t\treturn nil, fmt.Errorf(\"not authenticated\")\n")
			sb.WriteString("\t}\n")
		}

		sb.WriteString(fmt.Sprintf("\treturn %s.%s(%s)\n", pkg, s.FuncName, strings.Join(callArgs, ", ")))
		sb.WriteString("}\n\n")
	}

	// Class-level (static) query resolvers
	for _, q := range staticQueries {
		var goParams []string
		goParams = append(goParams, "ctx context.Context")
		var callArgs []string
		callArgs = append(callArgs, "ctx", "r.DB")
		for _, p := range q.Params {
			goParams = append(goParams, fmt.Sprintf("%s %s", p.Name, p.GoType))
			callArgs = append(callArgs, p.Name)
		}

		funcName := toPascalCase(q.QueryName)
		pkg := "models"
		if q.PackageName != "" {
			pkg = q.PackageName
		}

		if q.Description != "" {
			sb.WriteString(fmt.Sprintf("// %s %s\n", funcName, strings.ToLower(q.Description[:1])+q.Description[1:]))
		}

		retPkg := "models"
		if p, ok := serviceTypePackage[q.ReturnType]; ok {
			retPkg = p
		}

		if q.ReturnsList {
			sb.WriteString(fmt.Sprintf("func (r *queryResolver) %s(%s) ([]%s.%s, error) {\n",
				funcName, strings.Join(goParams, ", "), retPkg, q.ReturnType))
		} else {
			sb.WriteString(fmt.Sprintf("func (r *queryResolver) %s(%s) (*%s.%s, error) {\n",
				funcName, strings.Join(goParams, ", "), retPkg, q.ReturnType))
		}

		if !q.IsPublic && !adminMode {
			sb.WriteString("\tif connection.CurrentUser(ctx) == uuid.Nil {\n")
			sb.WriteString("\t\treturn nil, fmt.Errorf(\"not authenticated\")\n")
			sb.WriteString("\t}\n")
		}

		sb.WriteString(fmt.Sprintf("\treturn %s.%s(%s)\n", pkg, q.FuncName, strings.Join(callArgs, ", ")))
		sb.WriteString("}\n\n")
	}

	// Suppress unused imports. Defensive — emitted regardless of what
	// resolvers landed in this file, so models opting fully out of auto
	// CRUD/queries still produce a compilable shell. The blank-assigns
	// reference each imported package at least once.
	sb.WriteString("var _ context.Context\n")
	sb.WriteString("var _ = connection.CurrentUser\n")
	sb.WriteString("var _ = fmt.Errorf\n")
	sb.WriteString("var _ = uuid.Nil\n")
	sb.WriteString("var _ generated.PaginationInput\n")
	if anchor := anyModelName(models); anchor != "" {
		sb.WriteString(fmt.Sprintf("var _ models.%s\n", anchor))
		sb.WriteString(fmt.Sprintf("var _ = crud.FindByID[models.%s]\n\n", anchor))
	}

	return sb.String()
}

// anyModelName returns the first GraphQL-marked model's struct name, useful
// when emitting blank-assigns that reference the consumer's models package
// without knowing which specific model will be in scope.
func anyModelName(models []ModelDef) string {
	if len(models) > 0 {
		return models[0].Name
	}
	return ""
}

// collectServiceImports returns unique import paths from service-sourced static definitions.
func collectServiceImports(mutations []StaticMutationDef, queries []StaticQueryDef) []string {
	seen := make(map[string]bool)
	var imports []string
	for _, m := range mutations {
		if m.ImportPath != "" && !seen[m.ImportPath] {
			seen[m.ImportPath] = true
			imports = append(imports, m.ImportPath)
		}
	}
	for _, q := range queries {
		if q.ImportPath != "" && !seen[q.ImportPath] {
			seen[q.ImportPath] = true
			imports = append(imports, q.ImportPath)
		}
	}
	return imports
}

// GenerateResolverHelpers produces helper functions for pagination and input mapping.
func GenerateResolverHelpers(models []ModelDef, moduleName string) string {
	if moduleName == "" {
		moduleName = "core"
	}
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// Code generated by tools/gqlgen. DO NOT EDIT.\n// Helper functions for resolver implementations.\n\npackage resolver\n\nimport (\n\t\"%s/graph/generated\"\n\t\"reflect\"\n\t\"strings\"\n\t\"unicode\"\n)\n\n", moduleName))

	sb.WriteString(`// parsePagination extracts limit and offset from PaginationInput.
func parsePagination(p *generated.PaginationInput) (int, int) {
	limit := 25
	offset := 0
	if p != nil {
		if p.First != nil && *p.First > 0 {
			limit = *p.First
		}
		// Simple offset-based pagination for now.
		// Cursor-based can be added later.
	}
	return limit, offset
}

// toPageInfo creates a PageInfo response from pagination state.
func toPageInfo(totalCount int64, limit, offset int) *generated.PageInfo {
	hasNext := int64(offset+limit) < totalCount
	hasPrev := offset > 0
	total := int(totalCount)
	return &generated.PageInfo{
		HasNextPage:     hasNext,
		HasPreviousPage: hasPrev,
		TotalCount:      total,
	}
}

// toFilterMap converts a generated filter struct to a map for GORM Where().
// Only non-nil fields are included.
func toFilterMap(filter interface{}) map[string]interface{} {
	if filter == nil {
		return nil
	}
	result := make(map[string]interface{})
	v := reflect.ValueOf(filter)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return nil
		}
		v = v.Elem()
	}
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		field := v.Field(i)
		if field.Kind() == reflect.Ptr && field.IsNil() {
			continue
		}
		// Get the JSON tag name for the DB column
		jsonTag := t.Field(i).Tag.Get("json")
		if jsonTag == "" || jsonTag == "-" {
			continue
		}
		// Strip ",omitempty" etc.
		if idx := len(jsonTag); idx > 0 {
			for j, c := range jsonTag {
				if c == ',' {
					jsonTag = jsonTag[:j]
					break
				}
			}
		}
		col := camelToSnake(jsonTag)
		if field.Kind() == reflect.Ptr {
			result[col] = field.Elem().Interface()
		} else {
			result[col] = field.Interface()
		}
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

`)

	// Generic input-to-model and update mappers using reflection.
	// Works for all models without per-model code generation.
	sb.WriteString(`// inputToModel maps a gqlgen Create*Input struct to a GORM model using reflection.
// Fields are matched by JSON tag name. Handles embedded mixins transparently.
func inputToModel[T any](input interface{}) *T {
	var model T
	mapInputToStruct(input, &model)
	return &model
}

// camelToSnake converts a camelCase string to snake_case for GORM column names.
// "skillId" → "skill_id", "versionLabel" → "version_label"
func camelToSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// updateToMap converts a gqlgen Update*Input struct to a map[string]interface{}
// for GORM's Updates() method. Only non-nil pointer fields are included.
// Keys are converted from camelCase (gqlgen) to snake_case (GORM column names).
func updateToMap(input interface{}) map[string]interface{} {
	updates := make(map[string]interface{})
	v := reflect.ValueOf(input)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		field := v.Field(i)
		tag := t.Field(i).Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}
		// Strip ",omitempty"
		if idx := indexByte(tag, ','); idx >= 0 {
			tag = tag[:idx]
		}
		// Convert camelCase to snake_case for DB column names
		col := camelToSnake(tag)
		// Only include non-nil values
		if field.Kind() == reflect.Ptr && !field.IsNil() {
			updates[col] = field.Elem().Interface()
		} else if field.Kind() == reflect.Slice && !field.IsNil() {
			updates[col] = field.Interface()
		}
	}
	return updates
}

// normalizeTag converts a JSON tag (camelCase or snake_case) to a canonical
// lowercase form for comparison. "skillId" and "skill_id" both become "skillid".
func normalizeTag(tag string) string {
	var b strings.Builder
	for _, r := range tag {
		if r != '_' {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	return b.String()
}

// mapInputToStruct copies fields from input to model by matching JSON tag names.
// Handles the camelCase (gqlgen) vs snake_case (GORM) mismatch by normalizing tags.
func mapInputToStruct(input interface{}, model interface{}) {
	inputVal := reflect.ValueOf(input)
	if inputVal.Kind() == reflect.Ptr {
		inputVal = inputVal.Elem()
	}
	modelVal := reflect.ValueOf(model)
	if modelVal.Kind() == reflect.Ptr {
		modelVal = modelVal.Elem()
	}

	// Build a map of normalized_tag -> field value from input
	inputFields := make(map[string]reflect.Value)
	inputType := inputVal.Type()
	for i := 0; i < inputType.NumField(); i++ {
		tag := inputType.Field(i).Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}
		if idx := indexByte(tag, ','); idx >= 0 {
			tag = tag[:idx]
		}
		inputFields[normalizeTag(tag)] = inputVal.Field(i)
	}

	// Walk the model struct (including embedded structs) and set matching fields
	setFieldsRecursive(modelVal, inputFields)
}

func setFieldsRecursive(modelVal reflect.Value, inputFields map[string]reflect.Value) {
	modelType := modelVal.Type()
	for i := 0; i < modelType.NumField(); i++ {
		field := modelType.Field(i)
		fieldVal := modelVal.Field(i)

		// Recurse into embedded structs (mixins)
		if field.Anonymous && fieldVal.Kind() == reflect.Struct {
			setFieldsRecursive(fieldVal, inputFields)
			continue
		}

		tag := field.Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}
		if idx := indexByte(tag, ','); idx >= 0 {
			tag = tag[:idx]
		}

		inputField, exists := inputFields[normalizeTag(tag)]
		if !exists || !fieldVal.CanSet() {
			continue
		}

		// Handle pointer-to-value assignment
		if inputField.Kind() == reflect.Ptr {
			if inputField.IsNil() {
				continue
			}
			if fieldVal.Kind() == reflect.Ptr {
				fieldVal.Set(inputField)
			} else {
				fieldVal.Set(inputField.Elem())
			}
		} else {
			if fieldVal.Type() == inputField.Type() {
				fieldVal.Set(inputField)
			} else if fieldVal.Kind() == reflect.Ptr && inputField.Type() == fieldVal.Type().Elem() {
				ptr := reflect.New(inputField.Type())
				ptr.Elem().Set(inputField)
				fieldVal.Set(ptr)
			}
		}
	}
}

func indexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}

`)
	// No per-model mappers needed — the generic functions handle everything.

	return sb.String()
}

// preloadInfo describes what preloading a model needs.
type preloadInfo struct {
	// Standard GORM preload paths (non-Tenant, non-User associations).
	Paths []string
	// Whether to call EnrichTenants on the loaded items.
	EnrichTenants bool
	// Whether to call EnrichUsers on the loaded items.
	EnrichUsers bool
	// Has-many relationship fields whose items also need EnrichTenants.
	// e.g., "Memberships" means: for each item, enrich item.Memberships with tenants.
	NestedEnrich []string
}

// analyzePreloads inspects a model's relationships and determines what preloading
// strategy to use. Because GORM cannot resolve belongs_to foreign keys when both
// the source and target models share a field name (TenantID from TenantMixin vs
// Tenant.TenantID primary key), we use manual EnrichTenants / EnrichUsers
// instead of Preload for any Tenant or User association. User has the same
// problem as Tenant because it also embeds TenantMixin — Preload("User") from
// a tenanted source model picks the wrong join predicate and silently returns
// null for any row whose user.tenant_id doesn't happen to match the source row.
func analyzePreloads(m ModelDef) preloadInfo {
	var info preloadInfo
	for _, r := range m.Relationships {
		tag := r.GraphQLTag
		if tag == "" {
			continue
		}
		if r.GoType == "Tenant" && tag == "preload" {
			// Direct Tenant association — use manual enrichment, not GORM Preload.
			info.EnrichTenants = true
		} else if r.GoType == "User" && r.GoName == "User" && tag == "preload" {
			// Direct User association where the field is literally `User *User`
			// (FK = UserID). Both Membership and User embed TenantMixin, and
			// GORM's Preload picks the wrong join predicate when both source
			// and target share both `tenant_id` AND `user_id` columns. Manual
			// enrichment sidesteps it. Other `*User` associations with
			// distinct FK names (e.g. Agent.Owner/OwnerID, Agent.Maintainer/
			// MaintainerID) are unambiguous to GORM and still use Preload.
			info.EnrichUsers = true
		} else if tag == "preload" {
			// Non-Tenant, non-User association — standard GORM Preload.
			info.Paths = append(info.Paths, r.GoName)
		} else if strings.HasPrefix(tag, "preload:") {
			// Has-many with nested preloads. Preload the parent via GORM.
			info.Paths = append(info.Paths, r.GoName)
			// Check if any nested path is "Tenant" — those need manual enrichment.
			nested := strings.TrimPrefix(tag, "preload:")
			for _, part := range strings.Split(nested, ",") {
				part = strings.TrimSpace(part)
				if part == "Tenant" {
					info.NestedEnrich = append(info.NestedEnrich, r.GoName)
				} else if part != "" {
					// Non-Tenant nested preload — use standard GORM path.
					info.Paths = append(info.Paths, r.GoName+"."+part)
				}
			}
		}
	}
	return info
}

// toPascalCase converts snake_case to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			// Handle common acronyms
			upper := strings.ToUpper(parts[i])
			if upper == "ID" || upper == "URL" || upper == "API" || upper == "UUID" {
				parts[i] = upper
			} else {
				parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
			}
		}
	}
	return strings.Join(parts, "")
}
